### ISSUE TITLE
 May I ask where can I download the loongson jre of the mips64 architecture.

### ISSUE THREAD

**Issue by ChenyuWang98** [loongson/jdk#36]
May I ask where can I download the loongson jre of the mips64 architecture.

**Comment by theaoqi** [comment]
Which JDK/JRE version do you need? Do you need source code or JDK/JRE binary?

Generally, the upstream openjdk supports the Zero version of MIPS64. You can obtain the source code from the corresponding repository in [openjdk](https://github.com/openjdk). Loongson maintained and released MIPS64 JIT JDKs of some old versions such as [17, 11 and 8](http://www.loongnix.cn/zh/api/java), but Loongson didn't release JREs. In the current [repository](https://github.com/loongson/jdk), the MIPS64 JIT port is no longer contained.

**Comment by ChenyuWang98** [comment]
> Which JDK/JRE version do you need? Do you need source code or JDK/JRE binary?
> 
> Generally, the upstream openjdk supports the Zero version of MIPS64. You can obtain the source code from the corresponding repository in [openjdk](https://github.com/openjdk). Loongson maintained and released MIPS64 JIT JDKs of some old versions such as [17, 11 and 8](http://www.loongnix.cn/zh/api/java), but Loongson didn't release JREs. In the current [repository](https://github.com/loongson/jdk), the MIPS64 JIT port is no longer contained.


I need jre11 for mips64. 
Our products require cross-platform support, especially for Loongson(mips64) product packages, which require built-in jre11 runtime. Do you have any recommended way.
